name: Docker Build and Push

on:
    push:
        tags:
            - '*'
    pull_request:
        branches: [ main ]

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: esportsvideos/php

jobs:
    hadolint:
        name: Run Hadolint
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Run Hadolint
                uses: hadolint/hadolint-action@v3.1.0
                with:
                    dockerfile: Dockerfile

    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        needs: hadolint
        steps:
            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v3

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3

            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Log in to the Container registry
                if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
                uses: docker/login-action@v3
                with:
                    registry: ${{ env.REGISTRY }}
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Docker meta
                id: meta
                uses: docker/metadata-action@v5
                with:
                    images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                    labels: |
                        org.opencontainers.image.vendor=Esports-Videos
                        org.opencontainers.image.licenses=MIT
                        org.opencontainers.image.description=Production-ready PHP image used for API

            -   name: Docker meta dev
                id: meta-dev
                uses: docker/metadata-action@v5
                with:
                    images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                    flavor: |
                        latest=auto
                        suffix=-dev,onlatest=true
                    tags: |
                        type=ref,event=tag
                    labels: |
                        org.opencontainers.image.vendor=Esports-Videos
                        org.opencontainers.image.licenses=MIT
                        org.opencontainers.image.description=PHP image configured for API development and debugging.

            -   name: Build and push php-prod
                uses: docker/build-push-action@v6
                with:
                    provenance: false
                    context: .
                    target: php_prod
                    platforms: linux/amd64
                    labels: ${{ steps.meta.outputs.labels }}
                    cache-from: type=gha, scope=${{ github.workflow }}
                    cache-to: type=gha, scope=${{ github.workflow }}
                    push: ${{ github.event_name != 'pull_request' }}
                    tags: "${{ steps.meta.outputs.tags }}"

            -   name: Build and push php-dev
                uses: docker/build-push-action@v6
                with:
                    provenance: false
                    context: .
                    target: php_dev
                    platforms: linux/amd64
                    labels: ${{ steps.meta-dev.outputs.labels }}
                    cache-from: type=gha, scope=${{ github.workflow }}
                    cache-to: type=gha, scope=${{ github.workflow }}
                    push: ${{ github.event_name == 'push' && contains(github.ref, 'refs/tags/') }}
                    tags: "${{ steps.meta-dev.outputs.tags }}"
